name: Build

on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths-ignore:
      - docs
      - LICENSE
      - README.md
  pull_request:
    branches:
      - "*"

env:
  PROJECT_NAME: veeder_root_tls_socket_library

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 9
          submodules: false

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download dependencies
        run: |
          pip install -r requirements.txt
          python -m build
          pip install dist/*.whl

      - name: Run tests
        run: |
          cd tests
          python -m unittest
          cd ..

      - name: Upload distribution package
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    steps:
      - name: Download a distribution artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Use Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install twine

      - name: Publish distribution to PyPI
        run: |
          twine upload -r pypi dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.pypi_password }}