# Testing.

name: Testing

on:
  release:
    types: [published]
  push:
    branches:
      - main
    paths-ignore:
      - docs
      - LICENSE
      - README.md
  pull_request:
    branches:
      - "*"

env:
  TLS_IP: ${{ secrets.TLS_IP }}
  TLS_PORT: ${{ secrets.TLS_PORT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug environment variables
        run: |
          echo "TLS_IP: $TLS_IP"
          echo "TLS_PORT: $TLS_PORT"